spring:
  application:
    name: mappers-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123456
    url: jdbc:mysql://localhost:3306/test
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis-plus:
  mapper-locations: classpath:mappers/**Mapper.xml
