server:
  port: 8761
spring:
  application:
    name: register
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761
    register-with-eureka: false
#  server:
#    enable-self-preservation: false