spring:
  datasource:
    url: jdbc:mysql://localhost:3306/custom?characterEncoding=UTF-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver